//! `ivk init [--agent-instructions] [--json] [--agent]`
//!
//! Creates `.ivk/` skeleton in the current repo and (optionally) writes
//! AGENTS.md + skills/ivk/* into the target repo.
//!
//! Phase 1 deliverable. Idempotent: re-running on an initialized repo is a
//! no-op except for files that don't yet exist.

use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::output::{print_json, wants_agent, wants_json, Envelope, ErrorBlock};

#[derive(Serialize)]
struct InitPayload {
    repo_root: String,
    ivk_dir: String,
    files_created: Vec<String>,
    files_skipped: Vec<String>,
}

const CONFIG_TOML: &str = "\
# Ivy Kernel configuration.
# Auto-generated by `ivk init`; safe to edit.

[kernel]
# The materialization strategy ivk should use. `auto` picks per-OS:
#   macOS  -> apfs-clonefile
#   Linux  -> linux-reflink (cp --reflink=always)
# Override only if you know what you're doing.
strategy = \"auto\"

# Directory under the repo root where workspaces are materialized.
# Each workspace becomes a subdirectory: .ivk/workspaces/<name>/
workspaces_dir = \".ivk/workspaces\"
";

const AGENT_POLICY_TOML: &str = "\
# Agent policy for this repository.
# Editable. Used by `ivk doctor` to enforce repo-specific rules.

[agent]
# Hard rules surface as errors when doctor sees them violated.
must_use_workspaces = true       # agent must `ivk new` before editing
forbid_manual_worktrees = true   # `git worktree add` outside ivk is a violation
forbid_direct_push = true        # use `ivk export` / `ivk ship`, not raw push
";

pub fn run(args: &[&str]) -> i32 {
    let json = wants_json(args);
    let agent = wants_agent(args);
    let want_agent_files = args.contains(&"--agent-instructions");

    let cwd = match std::env::current_dir() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("ivk init: cannot resolve current directory: {}", e);
            return 1;
        }
    };
    if !cwd.join(".git").exists() {
        let msg = "current directory does not contain a .git/; `ivk init` must be run from a git repo root";
        if json || agent {
            let env: Envelope<()> = Envelope {
                ok: false,
                command: "init",
                next_command: Some("git init".into()),
                recommended_next_steps: None,
                error: Some(ErrorBlock {
                    code: "not_a_git_repo",
                    message: msg.into(),
                }),
                data: (),
            };
            print_json(&env);
        } else {
            eprintln!("ivk: {}", msg);
        }
        return 1;
    }

    let ivk_dir = cwd.join(".ivk");
    let mut created: Vec<String> = Vec::new();
    let mut skipped: Vec<String> = Vec::new();

    // .ivk skeleton
    for sub in [".ivk", ".ivk/workspaces", ".ivk/changesets"] {
        let p = cwd.join(sub);
        if !p.exists() {
            if let Err(e) = fs::create_dir_all(&p) {
                eprintln!("ivk: cannot create {}: {}", p.display(), e);
                return 1;
            }
            created.push(sub.to_string());
        } else {
            skipped.push(sub.to_string());
        }
    }

    write_if_absent(
        &ivk_dir.join("config.toml"),
        CONFIG_TOML,
        &mut created,
        &mut skipped,
    );
    write_if_absent(
        &ivk_dir.join("agent-policy.toml"),
        AGENT_POLICY_TOML,
        &mut created,
        &mut skipped,
    );

    if want_agent_files {
        write_if_absent(
            &cwd.join("AGENTS.md"),
            AGENTS_MD_TEMPLATE,
            &mut created,
            &mut skipped,
        );
        write_if_absent(
            &cwd.join("skills/ivk/SKILL.md"),
            include_str!("./assets/skills_SKILL.md"),
            &mut created,
            &mut skipped,
        );
        write_if_absent(
            &cwd.join("skills/ivk/cli.md"),
            include_str!("./assets/skills_cli.md"),
            &mut created,
            &mut skipped,
        );
        write_if_absent(
            &cwd.join("skills/ivk/workflow.md"),
            include_str!("./assets/skills_workflow.md"),
            &mut created,
            &mut skipped,
        );
        write_if_absent(
            &cwd.join("skills/ivk/mcp.md"),
            include_str!("./assets/skills_mcp.md"),
            &mut created,
            &mut skipped,
        );
        write_if_absent(
            &cwd.join("skills/ivk/rules/safety.md"),
            include_str!("./assets/skills_rules_safety.md"),
            &mut created,
            &mut skipped,
        );
    }

    if json || agent {
        let next = if created.is_empty() && skipped.iter().any(|s| s == ".ivk") {
            Some("ivk doctor --agent --json".into())
        } else {
            Some("ivk new <task-name>".into())
        };
        let steps = if agent {
            Some(vec![
                "`.ivk/` is now ready. Create a workspace per task with `ivk new <task-name>`.".into(),
                "If you skipped --agent-instructions, run `ivk init --agent-instructions` to also drop AGENTS.md and skills/ivk/.".into(),
            ])
        } else {
            None
        };
        let payload = InitPayload {
            repo_root: cwd.display().to_string(),
            ivk_dir: ivk_dir.display().to_string(),
            files_created: created,
            files_skipped: skipped,
        };
        let env = Envelope {
            ok: true,
            command: "init",
            next_command: next,
            recommended_next_steps: steps,
            error: None,
            data: payload,
        };
        print_json(&env);
    } else {
        println!("initialized .ivk/ in {}", cwd.display());
        for c in &created {
            println!("  + {}", c);
        }
        for s in &skipped {
            println!("  = {}", s);
        }
        if !want_agent_files {
            println!("\nTip: re-run with `--agent-instructions` to also generate AGENTS.md and skills/ivk/.");
        }
    }

    0
}

fn write_if_absent(
    path: &Path,
    content: &str,
    created: &mut Vec<String>,
    skipped: &mut Vec<String>,
) {
    let rel = relative_to_cwd(path);
    if path.exists() {
        skipped.push(rel);
        return;
    }
    if let Some(parent) = path.parent() {
        if let Err(e) = fs::create_dir_all(parent) {
            eprintln!("ivk: cannot create {}: {}", parent.display(), e);
            return;
        }
    }
    if let Err(e) = fs::write(path, content) {
        eprintln!("ivk: cannot write {}: {}", path.display(), e);
        return;
    }
    created.push(rel);
}

fn relative_to_cwd(p: &Path) -> String {
    if let Ok(cwd) = std::env::current_dir() {
        if let Ok(rel) = p.strip_prefix(&cwd) {
            return rel.display().to_string();
        }
    }
    p.display().to_string()
}

// AGENTS.md is small enough to ship inline. Skills files are pulled via
// include_str! from sibling asset copies (see crates/ivk-cli/src/assets/).
const AGENTS_MD_TEMPLATE: &str = include_str!("./assets/AGENTS.md");

// Compile-time check that the asset files exist.
fn _asset_check() {
    let _ = (
        AGENTS_MD_TEMPLATE.len(),
        include_str!("./assets/skills_SKILL.md").len(),
        include_str!("./assets/skills_cli.md").len(),
        include_str!("./assets/skills_workflow.md").len(),
        include_str!("./assets/skills_mcp.md").len(),
        include_str!("./assets/skills_rules_safety.md").len(),
    );
}

#[allow(dead_code)]
fn _force_path_use(_p: &PathBuf) {} // silence unused import in some configs
