#!/usr/bin/env bash
# Live disk-usage race: create N workspaces alternately via git worktree and
# via ivk (approach G), and redraw two horizontal bars after each pair so the
# disk consumption gap appears live, htop-style.
#
# Usage: scripts/bench/live-race.sh [N] [REPO]
#   N    = pairs of workspaces (default 20 — 20 git + 20 ivk = 40 total)
#   REPO = source repo path (default .cache/repo-M, generated by gen-repo.sh M)
#
# Designed to be recorded with vhs (see demos/disk-race.tape).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

N="${1:-20}"
REPO="${2:-$ROOT/.cache/repo-M}"
GIT_DIR="$ROOT/.cache/race-git"
IVK_DIR="$ROOT/.cache/race-ivk"
CREATE_ONE="$SCRIPT_DIR/create-one.sh"

if [[ ! -f "$REPO/.git/HEAD" ]]; then
  echo "ERROR: $REPO not found. Run scripts/bench/gen-repo.sh M first." >&2
  exit 2
fi

# Best-effort cleanup of any leftovers from a previous run.
for d in "$GIT_DIR" "$IVK_DIR"; do
  if [[ -d "$d" ]]; then
    for ws in "$d"/ws-*; do
      [[ -e "$ws" ]] || continue
      /usr/bin/git -C "$REPO" worktree remove --force "$ws" 2>/dev/null || true
    done
    /bin/rm -rf "$d"
  fi
done
/usr/bin/git -C "$REPO" worktree prune

/bin/mkdir -p "$GIT_DIR" "$IVK_DIR"

BAR_W=50
# Scale: max bar width = expected git worktree disk for N workspaces.
# repo-M is ~210 MB; assume 12 MB checkout overhead on top.
PER_WS_KB=$(( 220 * 1024 ))
MAX_KB=$(( N * PER_WS_KB ))

df_free_kb() { /bin/df -k "$1" | /usr/bin/awk 'NR==2 {print $4}'; }
fmt_mb() {
  local kb="$1"
  if (( kb < 1024 )); then printf "%4d KB" "$kb"
  elif (( kb < 1024 * 1024 )); then printf "%4d MB" "$(( kb / 1024 ))"
  else printf "%.2f GB" "$(/usr/bin/awk -v k="$kb" 'BEGIN{print k/1024/1024}')"
  fi
}

draw_bar() {
  local row="$1" label="$2" used_kb="$3" color="$4"
  local filled=$(( used_kb * BAR_W / MAX_KB ))
  (( filled > BAR_W )) && filled=$BAR_W
  (( filled < 0 )) && filled=0
  local empty=$(( BAR_W - filled ))

  /usr/bin/tput cup "$row" 0
  printf "\033[K"  # clear line
  printf "%-15s [" "$label"
  printf "\033[1;${color}m"
  /usr/bin/printf "█%.0s" $(/usr/bin/seq 1 "$filled" 2>/dev/null || true)
  printf "\033[0m"
  /usr/bin/printf " %.0s" $(/usr/bin/seq 1 "$empty" 2>/dev/null || true)
  printf "] "
  fmt_mb "$used_kb"
}

draw_status() {
  /usr/bin/tput cup 5 0
  printf "\033[K  %2d / %d workspaces of each created" "$1" "$N"
}

# Layout
clear
/usr/bin/tput civis  # hide cursor
trap '/usr/bin/tput cnorm; /usr/bin/tput cup 8 0' EXIT
printf "Disk consumed by N parallel workspaces (live)\n\n"
draw_bar 2 "git worktree" 0 31  # red
draw_bar 3 "ivk"          0 34  # blue
draw_status 0

git_used=0
ivk_used=0
for i in $(/usr/bin/seq 1 "$N"); do
  # git worktree
  before=$(df_free_kb "$GIT_DIR")
  /usr/bin/git -C "$REPO" worktree add -q --detach "$GIT_DIR/ws-$i" HEAD >/dev/null
  after=$(df_free_kb "$GIT_DIR")
  delta=$(( before - after ))
  (( delta < 0 )) && delta=0
  git_used=$(( git_used + delta ))
  draw_bar 2 "git worktree" "$git_used" 31

  # ivk (approach G via create-one.sh)
  before=$(df_free_kb "$IVK_DIR")
  /bin/bash "$CREATE_ONE" G "$REPO" "$IVK_DIR/ws-$i" >/dev/null
  after=$(df_free_kb "$IVK_DIR")
  delta=$(( before - after ))
  (( delta < 0 )) && delta=0
  ivk_used=$(( ivk_used + delta ))
  draw_bar 3 "ivk"          "$ivk_used" 34

  draw_status "$i"
done

# Final ratio line.
/usr/bin/tput cup 5 0
printf "\033[K  %2d / %d workspaces of each created\n" "$N" "$N"
/usr/bin/tput cup 6 0
ratio="-"
if (( ivk_used > 0 )); then
  ratio=$(/usr/bin/awk -v g="$git_used" -v i="$ivk_used" 'BEGIN{printf "%.1f", g/i}')x
fi
printf "\n  ivk uses %s less disk than git worktree for the same %d workspaces.\n" "$ratio" "$N"

# Cleanup the staged workspaces (keep the demo idempotent).
for i in $(/usr/bin/seq 1 "$N"); do
  /usr/bin/git -C "$REPO" worktree remove --force "$GIT_DIR/ws-$i" >/dev/null 2>&1 || true
  /usr/bin/git -C "$REPO" worktree remove --force "$IVK_DIR/ws-$i" >/dev/null 2>&1 || true
done
/bin/rm -rf "$GIT_DIR" "$IVK_DIR"
/usr/bin/git -C "$REPO" worktree prune
